# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [windows-latest]

    strategy:
      matrix:
        node-version: [12.x]
        #node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Cache node_modules
      id: cache-node_modules
      uses: actions/cache@v1
      with:
        path: ~\AppData\Roaming\npm-cache
        key: ${{ runner.os }}-node-${{ matrix.node-version }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i tfx-cli
    - run: .\node_modules\.bin\tfx extension create --output-path ..\out
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    #  env:
    #    CI: true
    - uses: actions/upload-artifact@v1
      with:
        name: vsix
        path: ..\out
